CREATE TABLE students IF NOT EXISTS
(
    id      bigint generated by default as identity
        primary key,
    email   varchar(255),
    name    varchar(255),
    surname varchar(255)
);
CREATE TABLE homeworks IF NOT EXISTS
(
    deadline    date,
    mark        integer,
    id          bigint generated  as identity primary key,
    student_id  bigint not null,
    FOREIGN KEY (student_id) REFERENCES students(id),
    description varchar(255)
    );